default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>


development:
  <<: *default
  database: payment_demo_development

test:
  <<: *default
  database: payment_demo_test
production:
  <<: *default
  database: payment_demo_production
  
